version: '3.8'
services:  
  be:    
    image: a9052681569/budget-stuff-be
    # build: ../be
    depends_on:
      - mongodb
    container_name: be
    pull_policy: always
    ports:      
      - '3000:3000'
    restart: always
    env_file:
      - ./.env
  fe:
    image: a9052681569/budget-stuff-web
    # build: ../web
    container_name: fe
    pull_policy: always
    ports:      
      - '8080:8080'
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb  
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw